services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: game_list
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: spring-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/game_list
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
